INSERT INTO flight (description, from_airport, to_airport, status,) VALUES
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('Marco', 'Berlino', 'Milano-Malpensa','ONTIME'),
('Elena', 'Heathrow', 'Cagliari','DELAYED'),
('last-minute', 'Baku', 'Jakartha','CANCELLED'),
('Davide', 'Greco', 'CLIENTE','ONTIME'),
('Chiara', 'Fontana', 'CLIENTE','DELAYED'),
('Alessandro', 'Ferrari','OPERATORE','DELAYED'),
('Martina', 'Conti','CLIENTE','CANCELLED'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('Francesco', 'Gallo','CLIENTE','CANCELLED');