INSERT INTO flight (description, from_airport, to_airport, status) VALUES
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('europeo', 'Berlino', 'Milano-Malpensa','ONTIME'),
('internazionale', 'Heathrow', 'Cagliari','DELAYED'),
('last-minute', 'Baku', 'Jakartha','CANCELLED'),
('nazionale', 'Istanbul', 'Ankara','ONTIME'),
('internazionale', 'Palermo', 'Marrakech','DELAYED'),
('con scalo', 'New York','Ryhad','DELAYED'),
('con scali', 'Buenos Aires','Madrid','CANCELLED'),
('nazionale', 'Washigton','Madison','DELAYED'),
('diretto','La Paz','Asuncion','ONTIME'),
('con scali', 'Lusaka', 'Tripoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('intercontinentale','Reykjavick','Tel Aviv','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('senza scali','Montevideo','Lima','ONTIME'),
('diretto', 'Fiumicino-Roma', 'Lussemburgo','DELAYED'),
('con scali','Santiago','Caracas','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('intercontinentale','Taipei','Tehran','ONTIME'),
('nazionale,breve', 'Shangai', 'Pechino','DELAYED'),
('intercontinentale','Pechino','San Pietroburgo','ONTIME'),
('intercontinentale', 'Sidney','Seoul','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('con scali', 'Ottawa', 'Tokyo','DELAYED'),
('con scali','Brasilia','Città del Messico','ONTIME'),
('diretto', 'Miami', 'L Avana','DELAYED'),
('senza scali','Bruxelles','Varsavia','ONTIME'),
('nazionale,breve', 'Torino', 'Bari','DELAYED'),
('senza scali','Amsterdam','Francoforte','ONTIME'),
('nazionale,breve', 'Fiumicino-Roma', 'Napoli','DELAYED'),
('diretto','Rabat','Barcellona','ONTIME'),
('diretto', 'Milano-Malpensa','Parigi','CANCELLED');